config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "cats#index"

  resources :cats, except: [:destroy] do 
    resource :cat_rental_requests, only: [:new]
  end

  get '/delete/:id', to: 'cats#destroy', as: 'delete_cat'

  resources :cat_rental_requests, only: [:new, :create]
  
end

app/models/Cat.rb
require 'date'

class Cat < ApplicationRecord

    include ActionView::Helpers::DateHelper

    CAT_COLORS = ["brown", "tortuga", "white", "void","orange"]

    validates :birth_date, :color, :name, :sex, presence: true
    validates :color, inclusion: { in: CAT_COLORS }
    validates :sex, inclusion: {in: ["M", "F"] }
    validate :birth_date_cannot_be_future

    has_many :rental_requests,
        foreign_key: :cat_id,
        class_name: :CatRentalRequest,
        dependent: :destroy

    def birth_date_cannot_be_future
        if birth_date > Date.today
            errors.add(:birth_date, "birth date cannot be in the future")
        end
    end

    def age
        now = Date.today
        d = Date.parse(self.birth_date.to_s)
        before = Date.civil(d.year, d.mon, d.day)
        difference_in_days = (now - before).to_i
        # difference_in_days/365

        time_ago_in_words(Time.now - difference_in_days.days)
    end
    
end

app/models/CatRentalRequest.rb
class CatRentalRequest < ApplicationRecord
    validates :status, :start_date, :end_date, :cat_id, presence: true

    validates :status, inclusion: ["PENDING","APPROVED","DENIED"]

    validate :does_not_overlap_approved_request

    belongs_to :cat

    def overlapping_requests
        CatRentalRequest.where("(start_date BETWEEN ? AND ?) OR (end_date BETWEEN ? AND ?)", start_date, end_date, start_date, end_date)
    end

    def overlapping_approved_requests
        self.overlapping_requests.where("status = ?", "APPROVED")
    end

    def does_not_overlap_approved_request
        if self.overlapping_approved_requests.exists?
            errors.add(:start_date, "overlapping dates with other request")
        end
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

    def new
        @cats = Cat.all
        if params[:cat_id]
            @cat = Cat.find_by(id: params[:cat_id])
        end
        @cat_rental_request = CatRentalRequest.new
    end

    def create
        @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)
        if @cat_rental_request.save
            redirect_to cat_url(@cat_rental_request.cat_id)
        else
            @requested = false
            redirect_to new_cat_cat_rental_requests_url(@cat_rental_request.cat_id)
        end
    end

    private
    def cat_rental_request_params
        params.require(:cat_rental_request).permit(:status, :start_date, :end_date, :cat_id)
    end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

#index
    def index
        @cats = Cat.all
    end

#new
    def new
        @cat = Cat.new
    end

#edit
    def edit
        @cat = Cat.find_by(id: params[:id])
    end

#update
    def update
        @cat = Cat.find_by(id: params[:id])
        if @cat.update(cat_params)
            redirect_to cat_url(@cat)
        else
            render json: @cat.errors.full_messages, status: 422
        end
    end

#create
    def create
        @cat = Cat.new(cat_params)
        if @cat.save
            redirect_to cat_url(@cat) # , status: 201
        else
            render json: @cat.errors.full_messages, status: 422
        end
    end

#show
    def show
        @cat = Cat.find_by(id: params[:id])
    end

private
    def cat_params
        params.require(:cat).permit(:description, :name, :birth_date, :sex, :color)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cat_rental_requests/new.html.erb
<a href="<%= cats_url %>">back to index</a>
<h1>Rent <%= @cat.nil? ? "a cat" : @cat.name %></h1>
<% unless @requested %>
    <div class="error"><%= "ERROR: " + @cat.name + " is already being rented in the selected date range" %></div>
<% end %>
<form action="<%= cat_rental_requests_url %>" method="POST">
    <label>Cat
    <select name="cat_rental_request[cat_id]" required>
        <option disabled <%= "selected" if @cat.nil? %>>Select cat</option>
        <% @cats.each do |cat| %>
            <option value="<%= cat.id %>" <%= "selected" if @cat && @cat.name == cat.name %>><%= cat.name %></option>
        <% end %>
    </select></label>
    <label>Start date
    <input type="date" name="cat_rental_request[start_date]" placeholder="Starting on" value="<%= @cat_rental_request.start_date %>" required></label>
    <label>End Date
    <input type="date" name="cat_rental_request[end_date]" placeholder="Ending on" value="<%= @cat_rental_request.end_date %>" required></label>

    <button>Rent</button>

</form>

app/views/cats/_form.html.erb
<% path = action == :new ? cats_url : cat_url(cat) %>
<% submit = action == :new ? "create" : "update"%>

<form action="<%= path %>" method="POST">
    <% if action == :edit %>
     <input type="hidden" name="_method" value="PATCH">
    <% end %>
    <label>Name
    <input type="text" name="cat[name]" placeholder="Cat's name" value="<%= @cat.name %>"></label>
    <label>Birth Date
    <input type="date" name="cat[birth_date]" placeholder="Birth date" value="<%= @cat.birth_date %>"></label>
    <label>Color
    <select name="cat[color]">
        <option disabled <%= "selected" if @cat.color.nil? %>>Select color</option>
        <option <%= "selected" if @cat.color == "brown" %>>brown</option>
        <option <%= "selected" if @cat.color == "tortuga" %>>tortuga</option>
        <option <%= "selected" if @cat.color == "white" %>>white</option>
        <option <%= "selected" if @cat.color == "void" %>>void</option>
        <option <%= "selected" if @cat.color == "orange" %>>orange</option>
    </select></label>
    <label> Gender
    <input type="radio" name="cat[sex]" value="M" <%= "checked" if @cat.sex == "M" %>> Male
    <input type="radio" name="cat[sex]" value="F" <%= "checked" if @cat.sex == "F" %>> Female
    </label>
    <textarea name="cat[description]" placeholder="Description"><%= @cat.description || "" %></textarea>

    <button><%= submit %></button>

</form>

    <a href= "<%= path %>">cancel</a>

app/views/cats/edit.html.erb
<h1>Edit cat</h1>

<%= render "form", action: :edit, cat: @cat %>

app/views/cats/index.html.erb
<h1>Cats</h1>
<ul>
<% @cats.each do |cat| %>
    <li><a href="<%= cat_url(cat) %>"><%= cat.name %></a></li>
<% end %>
</ul>
<p><a href="<%= new_cat_url %>">Create cat</a></p>
<p><a href="<%= new_cat_rental_request_url() %>">Rent a cat</a></p>

app/views/cats/new.html.erb
<h1>New cat</h1>

<%= render "form", action: :new, cat: @cat %>

app/views/cats/show.html.erb
<a href="<%= cats_url %>">back to index</a>
<h1>Stats for <%= @cat.name %></h1>
<ul>
    <li>Name: <%= @cat.name %></li>
    <li>Age: <%= @cat.age %></li>
    <li>Color: <%= @cat.color %></li>
    <li>Gender: <%= @cat.sex %></li>
    <% if @cat.description != "" || !@cat.description.nil? %>
        <li><%= @cat.description %></li>
    <% end %>
</ul>
<a href="<%= edit_cat_url(@cat)%>">edit cat</a>

<h2>Rent Requests</h2>
<table>
    <thead>
        <tr>
            <td>Start date</td>
            <td>End date</td>
            <td>Status</td>
        </tr>
    </thead>
    <tbody>
        <% if @cat.rental_requests.empty? %>
            <tr>
                <td colspan="3">
                    <%= @cat.name + " has no rent requests" %>
                </td>
            </tr>
        <% else %>
            <% @cat.rental_requests.order(:start_date).each do |crr| %>
                <tr>
                    <td><%= crr.start_date %></td>
                    <td><%= crr.end_date %></td>
                    <td><%= crr.status %></td>
                </tr>
            <% end %>
        <% end %>
    </tbody>
</table>

<p><a href="<%= new_cat_cat_rental_requests_url(@cat) %>">rent <%= @cat.name %></a></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nineninecats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>